### PR TITLE
updated to respect the bowerrc in the cwd passed in as command line argument

### PR DESCRIPTION
**Pull request by ryantemple**
This fixes issue bower/bower#1993

### CODE REVIEW

**Comment by paulohp** [comment]
Looks Good! Thanks @ryantemple to spent some time here! :tada: :balloon: :+1: 

Anyone else wants to take a look? @sheerun @faceleg @bower/bower-volunteers ?

**Comment by faceleg** [comment]
This looks good to me, great to see you adding tests in with your first commit~

**Comment by sheerun** [comment]
@faceleg @riyadhalnur This is wrong fix as .bowerrc from --config.cwd overrides env variables. Please revert. Isn't the proper fix to just set `cwd` variable to `argvConfig.cwd`?

**Comment by riyadhalnur** [comment]
@sheerun I think this is the proper fix but just for good measure I opened a revert PR for this and assigned you to it.

**Comment by ryantemple** [comment]
I suppose with the fix as I've done it the .bowerrc in the directory the command is run from will be considered which is incorrect behaviour, the test is a valid one though.  Will create a new PR for this.

**Comment by ryantemple** [comment]
bower/config#40 fixes in the suggested way.

**Pull request merged**
