### PR TITLE
Added newer Node versions to Travis

### PR DESCRIPTION
**Pull request by riyadhalnur**
ADDED/UPDATED:
- Updated Travis file to not test against `iojs` anymore
- Added versions 4 and 5 of Node to test against on Travis

### CODE REVIEW

**Comment by paulohp** [comment]
@riyadhalnur hi, thanks to pay attention at this! Can you update the versions to cover on demand versions? https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Provided-Node.js-Versions

thanks.

**Comment by riyadhalnur** [comment]
@paulohp do you mean adding not just the latest versions of every major version but also the rest of the releases for a version?

**Comment by paulohp** [comment]
What you guys think @sheerun @faceleg ? I would to say more versions covered here.

**Comment by riyadhalnur** [comment]
There isn't a risk of breaking stuff when versions jump from 4.0.x to 4.2.x but from 4.x to 5.x, there are possibilities. Would love to get some more input though.

**Comment by sheerun** [comment]
It's probably enough :)

**Pull request merged**
