### PR TITLE
Updated so cwd is set from command line and correct directory tree used

### PR DESCRIPTION
**Pull request by ryantemple**
This should ensure that rc correctly sets the cwd from the command line if it is supplied.

### CODE REVIEW

**Comment by sheerun** [comment]
We need tests for it

**Comment by ryantemple** [comment]
No idea why tests haven't added - they were same as before. Will update shortly

**Comment by ryantemple** [comment]
@sheerun test added

**Comment by sheerun** [comment]
Looks good, thank you :)

**Pull request merged**
