### PR TITLE
Fixes bower/bower#1689 and actually adds tests and testing ability

### PR DESCRIPTION
**Pull request by kodypeterson**

### CODE REVIEW

**Comment by sheerun** [comment]
Hey. That's not exactly how it should work :)

Let's say you have following files

```js
// .bowerrc
{ foo: 'bar', fiz: 'fuz' }
```

```js
// child_with_foo/.bowerrc
{ foo: 'child bar' }
```

```js
// child_with_fiz/.bowerrc
{ fiz: 'child fiz' }
```

Then if you run `bower` in `child_with_foo` directory, the configuration should read:

```
{ foo: 'child bar', fiz: 'fuz' }
```

And if you run `bower` in `child_with_fiz` directory, the configuration should read:

```
{ foo: 'bar', fiz: 'child fiz' }
```

So we merge configs downwards the directory tree only. We don't need `**/.bowerrc` glob. 

`find` should recurse downwards directory tree only

Hope it helps!

**Comment by kodypeterson** [comment]
@sheerun Alright, should be an easy fix! :)

I will resolve the issues and add tests to support them :smile:

**Comment by kodypeterson** [comment]
Alright, @sheerun all fixed and tests to support the use cases! :smile:

**Comment by sheerun** [comment]
Looks good! Just one more thing: do we really need extra dependencies?

Could move what you can to `devDependencies`?

Also `glob` is probably no longer necessary in both comment and as dependency.

**Comment by kodypeterson** [comment]
@sheerun the extra dependencies have been moved to dev as they are only needed for tests and test helpers. Also removed the glob comment.

**Comment by sheerun** [comment]
Looks good :) Thank you

**Comment by itonics-tbeauvais** [comment]
Can someone please explain to me why bower should like to the parent directory for configuration?!

**Pull request merged**
